import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { initializeApp } from "firebase/app";
import { getAnalytics, isSupported } from "firebase/analytics";

export default function Home() {

  const [displaying, setDisplaying] = useState("about")
  // Import the functions you need from the SDKs you need

  
  const firebaseConfig = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
    measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
  };

  // Initialize Firebase
  const app = initializeApp(firebaseConfig);
  let analytics

  if (app.name && typeof window !== 'undefined' && isSupported) {
    analytics = getAnalytics(app);
  }



  return (
    <>
      <Head>
        <title>Ahmed Issaoui - Author, Developer & Entrepreneur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com/"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet"/>
      </Head>


    {/* - #MAIN */}

    <main>

      {/* - #SIDEBAR */}

        <aside className="sidebar" data-sidebar>

          <div className="sidebar-info">

            <figure className="avatar-box">
              <img src="./assets/images/my-avatar.png" alt="Richard hanrick" width="80"/>
            </figure>

            <div className="info-content">
              <h1 className="name" title="Ahmed Issaoui">Ahmed Issaoui</h1>
              <div className="titleContainer">
                <p className="title">Multi-specialist</p>
                <p className="title">Author</p>
                <p className="title">Developer</p>
                <p className="title">Entrepreneur</p>
              </div>
            </div>

            <button className="info_more-btn" data-sidebar-btn>
              <span>Show Contacts</span>

              <ion-icon name="chevron-down"></ion-icon>
            </button>

          </div>

          <div className="sidebar-info_more">

            <div className="separator"></div>

            <ul className="contacts-list">

              <li className="contact-item">

                <div className="icon-box">
                  <ion-icon name="mail-outline"></ion-icon>
                </div>

                <div className="contact-info">
                  <p className="contact-title">Email</p>

                  <a href="mailto:hello@ahmedissaoui.com" className="contact-link">hello@ahmedissaoui.com</a>
                </div>

              </li>

              <li className="contact-item">

                <div className="icon-box">
                  <ion-icon name="phone-portrait-outline"></ion-icon>
                </div>

                <div className="contact-info">
                  <p className="contact-title">Phone</p>
                  <a href="tel:+21626417576" className="contact-link">+216 26 417 576</a>
                </div>

              </li>

              
            <li className="contact-item">

              <div className="icon-box">
                <ion-icon name="calendar-outline"></ion-icon>
              </div>

              <div className="contact-info">
                <p className="contact-title">Current Status</p>

                <time >Open to Work (Senior Positions)</time>
              </div>

              </li>

              <li className="contact-item">

              <div className="icon-box">
                <ion-icon name="location-outline"></ion-icon>
              </div>

              <div className="contact-info">
                <p className="contact-title">Current Location</p>

                <address>Tunis, Tunisia</address>
              </div>

              </li>

            </ul>

            <div className="separator"></div>

            <ul className="social-list">

              <li className="social-item">
                <a href="https://www.linkedin.com/in/ahmed-issaoui1/" target="_blank" className="social-link">
                  <ion-icon name="logo-linkedin"></ion-icon>
                </a>
              </li>
              <li className="social-item">
                <a href="https://github.com/ahmed-issaoui" target="_blank" className="social-link">
                  <ion-icon name="logo-github"></ion-icon>
                </a>
              </li>

              <li className="social-item">
                <a href="https://dribbble.com/ahmed_issaoui" target="_blank" className="social-link">
                  <ion-icon name="logo-dribbble"></ion-icon>
                </a>
              </li>


            </ul>

          </div>

        </aside>





      {/* - #main-content */}

      <div className="main-content">

          {/* - #NAVBAR */}

            <nav className="navbar">

              <ul className="navbar-list">

                <li className="navbar-item">
                  <button className={`navbar-link ${displaying=="about" ? "active" : ""}`} data-nav-link onClick={()=> setDisplaying("about")}>About</button>
                </li>

                {/* <li className="navbar-item">
                  <button className={`navbar-link ${displaying=="resume" ? "active" : ""}`} data-nav-link onClick={()=> setDisplaying("resume")}>Resume</button>
                </li> */}

                {/* <li className="navbar-item">
                  <button className={`navbar-link ${displaying=="portfolio" ? "active" : ""}`} data-nav-link onClick={()=> setDisplaying("portfolio")}>Portfolio</button>
                </li> */}

                {/* <li className="navbar-item">
                  <button className={`navbar-link ${displaying=="blog" ? "active" : ""}`} data-nav-link onClick={()=> setDisplaying("blog")}>Blog</button>
                </li> */}

                <li className="navbar-item">
                  <button className={`navbar-link ${displaying=="contact" ? "active" : ""}`} data-nav-link onClick={()=> setDisplaying("contact")}>Contact</button>
                </li>

              </ul>

            </nav>





          {/* - #ABOUT */}
            <article className={`about ${displaying=="about" ? "active" : ""}`} data-page="about">

              <header>
                <h2 className="h2 article-title">About me</h2>
              </header>

              <section className="about-text">
                <p>
                  I'm a purpose driven entrepreneur and author working between the startup and the consulting worlds. I have written a cutting-edge book about business called Startup for Breakfast and I have preached and trained thousands of people in many fields from business, to tech to design. 
                </p>

              </section>


                {/* - service */}

              <section className="service">

                <h3 className="h3 service-title">Areas of Expertise</h3>

                <ul className="service-list">

                
                  <li className="service-item">

                    <div className="service-icon-box">
                      <img src="./assets/images/icon-entrepreneurship.svg" alt="camera icon" width="40"/>
                    </div>

                    <div className="service-content-box">
                      <h4 className="h4 service-item-title">Entrepreneurship</h4>

                      <p className="service-item-text">
                        Turning ideas, very innovative ideas, into successful and high impacting ventures.
                      </p>
                    </div>

                  </li>
                  <li className="service-item">

                    <div className="service-icon-box">
                      <img src="./assets/images/icon-marketing.svg
                      " alt="design icon" width="40"/>
                    </div>

                    <div className="service-content-box">
                      <h4 className="h4 service-item-title">Marketing & Sales</h4>

                      <p className="service-item-text">
                        I do it meaningful. I do it clever. I do it viral. But mostly I do it automated.
                      </p>
                    </div>

                  </li>

                  <li className="service-item">

                    <div className="service-icon-box">
                      <img src="./assets/images/icon-software.svg" alt="Web development icon" width="40"/>
                    </div>

                    <div className="service-content-box">
                      <h4 className="h4 service-item-title">Software Development</h4>

                      <p className="service-item-text">
                        Developing cutting edge technologies to tackle the world most painful problems.                      </p>
                    </div>

                  </li>

                  <li className="service-item">

                    <div className="service-icon-box">
                      <img src="./assets/images/icon-ai.svg" alt="mobile app icon" width="40"/>
                    </div>

                    <div className="service-content-box">
                      <h4 className="h4 service-item-title">Artificial Intelligence</h4>

                      <p className="service-item-text">
                        From generative to predictive conversational AI, tech boundaries are being challenged.
                      </p>
                    </div>

                  </li>

                  <li className="service-item">

                    <div className="service-icon-box">
                      <img src="./assets/images/icon-uiux.svg
                      " alt="design icon" width="40"/>
                    </div>

                    <div className="service-content-box">
                      <h4 className="h4 service-item-title">UI UX Design</h4>

                      <p className="service-item-text">
                        Creating engaging and intuitive products that enhance user experience and drive conversions.
                      </p>
                    </div>

                  </li>

                  <li className="service-item">

                    <div className="service-icon-box">
                      <img src="./assets/images/icon-growthhacking.svg
                      " alt="design icon" width="40"/>
                    </div>

                    <div className="service-content-box">
                      <h4 className="h4 service-item-title">Growth Hacking</h4>

                      <p className="service-item-text">
                        Leveraging innovation and guerilla strategies to accelerate growth and increase revenue.
                      </p>
                    </div>

                  </li>

                  

                </ul>

              </section>






                {/* - clients */}

              <section className="clients">

                <h3 className="h3 clients-title">Current Projects</h3>

                <ul className="clients-list has-scrollbar">

                  <li className="clients-item">
                    <a href="#">
                      <img src="./assets/images/logo-highscale.png" alt="highscale logo"/>
                    </a>
                  </li>

                  <li className="clients-item">
                    <a href="#">
                      <img src="./assets/images/logo-superlazy.png" alt="superlazy logo"/>
                    </a>
                  </li>

                  

                </ul>

              </section>

            </article>

          {/* - #RESUME */}

            {/* <article  className={`resume ${displaying=="resume" ? "active" : ""}`} data-page="resume">

              <header>
                <h2 className="h2 article-title">Resume</h2>
              </header>

              <section className="timeline">

                <div className="title-wrapper">
                  <div className="icon-box">
                    <ion-icon name="book-outline"></ion-icon>
                  </div>

                  <h3 className="h3">Education</h3>
                </div>

                <ol className="timeline-list">

                  <li className="timeline-item">

                    <h4 className="h4 timeline-item-title">University school of the arts</h4>

                    <span>2007 — 2008</span>

                    <p className="timeline-text">
                      Nemo enims ipsam voluptatem, blanditiis praesentium voluptum delenit atque corrupti, quos dolores et
                      quas molestias
                      exceptur.
                    </p>

                  </li>

                  <li className="timeline-item">

                    <h4 className="h4 timeline-item-title">New york academy of art</h4>

                    <span>2006 — 2007</span>

                    <p className="timeline-text">
                      Ratione voluptatem sequi nesciunt, facere quisquams facere menda ossimus, omnis voluptas assumenda est
                      omnis..
                    </p>

                  </li>

                  <li className="timeline-item">

                    <h4 className="h4 timeline-item-title">High school of art and design</h4>

                    <span>2002 — 2004</span>

                    <p className="timeline-text">
                      Duis aute irure dolor in reprehenderit in voluptate, quila voluptas mag odit aut fugit, sed consequuntur
                      magni dolores
                      eos.
                    </p>

                  </li>

                </ol>

              </section>

              <section className="timeline">

                <div className="title-wrapper">
                  <div className="icon-box">
                    <ion-icon name="book-outline"></ion-icon>
                  </div>

                  <h3 className="h3">Experience</h3>
                </div>

                <ol className="timeline-list">

                  <li className="timeline-item">

                    <h4 className="h4 timeline-item-title">Creative director</h4>

                    <span>2015 — Present</span>

                    <p className="timeline-text">
                      Nemo enim ipsam voluptatem blanditiis praesentium voluptum delenit atque corrupti, quos dolores et qvuas
                      molestias
                      exceptur.
                    </p>

                  </li>

                  <li className="timeline-item">

                    <h4 className="h4 timeline-item-title">Art director</h4>

                    <span>2013 — 2015</span>

                    <p className="timeline-text">
                      Nemo enims ipsam voluptatem, blanditiis praesentium voluptum delenit atque corrupti, quos dolores et
                      quas molestias
                      exceptur.
                    </p>

                  </li>

                  <li className="timeline-item">

                    <h4 className="h4 timeline-item-title">Web designer</h4>

                    <span>2010 — 2013</span>

                    <p className="timeline-text">
                      Nemo enims ipsam voluptatem, blanditiis praesentium voluptum delenit atque corrupti, quos dolores et
                      quas molestias
                      exceptur.
                    </p>

                  </li>

                </ol>

              </section>

              <section className="skill">

                <h3 className="h3 skills-title">My skills</h3>

                <ul className="skills-list content-card">

                  <li className="skills-item">

                    <div className="title-wrapper">
                      <h5 className="h5">Web design</h5>
                      <data value="80">80%</data>
                    </div>

                    <div className="skill-progress-bg">
                      <div className="skill-progress-fill" style={{width: "80%"}}></div>
                    </div>

                  </li>

                  <li className="skills-item">

                    <div className="title-wrapper">
                      <h5 className="h5">Graphic design</h5>
                      <data value="70">70%</data>
                    </div>

                    <div className="skill-progress-bg">
                      <div className="skill-progress-fill" style={{width: "70%"}}></div>
                    </div>

                  </li>

                  <li className="skills-item">

                    <div className="title-wrapper">
                      <h5 className="h5">Branding</h5>
                      <data value="90">90%</data>
                    </div>

                    <div className="skill-progress-bg">
                      <div className="skill-progress-fill" style={{width: "90%"}}></div>
                    </div>

                  </li>

                  <li className="skills-item">

                    <div className="title-wrapper">
                      <h5 className="h5">WordPress</h5>
                      <data value="50">50%</data>
                    </div>

                    <div className="skill-progress-bg">
                      <div className="skill-progress-fill" style={{width: "50%"}}></div>
                    </div>

                  </li>

                </ul>

              </section>

            </article> */}

          {/* - #PORTFOLIO */}

            {/* <article className={`portfolio ${displaying=="portfolio" ? "active" : ""}`} data-page="portfolio">

              <header>
                <h2 className="h2 article-title">Portfolio</h2>
              </header>

              <section className="projects">

                <ul className="filter-list">

                  <li className="filter-item">
                    <button className="active" data-filter-btn>All</button>
                  </li>

                  <li className="filter-item">
                    <button data-filter-btn>Web design</button>
                  </li>

                  <li className="filter-item">
                    <button data-filter-btn>Applications</button>
                  </li>

                  <li className="filter-item">
                    <button data-filter-btn>Web development</button>
                  </li>

                </ul>

                <div className="filter-select-box">

                  <button className="filter-select" data-select>

                    <div className="select-value" data-selecct-value>Select category</div>

                    <div className="select-icon">
                      <ion-icon name="chevron-down"></ion-icon>
                    </div>

                  </button>

                  <ul className="select-list">

                    <li className="select-item">
                      <button data-select-item>All</button>
                    </li>

                    <li className="select-item">
                      <button data-select-item>Web design</button>
                    </li>

                    <li className="select-item">
                      <button data-select-item>Applications</button>
                    </li>

                    <li className="select-item">
                      <button data-select-item>Web development</button>
                    </li>

                  </ul>

                </div>

                <ul className="project-list">

                  <li className="project-item  active" data-filter-item data-category="web development">
                    <a href="#">

                      <figure className="project-img">
                        <div className="project-item-icon-box">
                          <ion-icon name="eye-outline"></ion-icon>
                        </div>

                        <img src="./assets/images/project-1.jpg" alt="finance" loading="lazy"/>
                      </figure>

                      <h3 className="project-title">Finance</h3>

                      <p className="project-category">Web development</p>

                    </a>
                  </li>

                  <li className="project-item  active" data-filter-item data-category="web development">
                    <a href="#">

                      <figure className="project-img">
                        <div className="project-item-icon-box">
                          <ion-icon name="eye-outline"></ion-icon>
                        </div>

                        <img src="./assets/images/project-2.png" alt="orizon" loading="lazy"/>
                      </figure>

                      <h3 className="project-title">Orizon</h3>

                      <p className="project-category">Web development</p>

                    </a>
                  </li>

                  <li className="project-item  active" data-filter-item data-category="web design">
                    <a href="#">

                      <figure className="project-img">
                        <div className="project-item-icon-box">
                          <ion-icon name="eye-outline"></ion-icon>
                        </div>

                        <img src="./assets/images/project-3.jpg" alt="fundo" loading="lazy"/>
                      </figure>

                      <h3 className="project-title">Fundo</h3>

                      <p className="project-category">Web design</p>

                    </a>
                  </li>

                  <li className="project-item  active" data-filter-item data-category="applications">
                    <a href="#">

                      <figure className="project-img">
                        <div className="project-item-icon-box">
                          <ion-icon name="eye-outline"></ion-icon>
                        </div>

                        <img src="./assets/images/project-4.png" alt="brawlhalla" loading="lazy"/>
                      </figure>

                      <h3 className="project-title">Brawlhalla</h3>

                      <p className="project-category">Applications</p>

                    </a>
                  </li>

                  <li className="project-item  active" data-filter-item data-category="web design">
                    <a href="#">

                      <figure className="project-img">
                        <div className="project-item-icon-box">
                          <ion-icon name="eye-outline"></ion-icon>
                        </div>

                        <img src="./assets/images/project-5.png" alt="dsm." loading="lazy"/>
                      </figure>

                      <h3 className="project-title">DSM.</h3>

                      <p className="project-category">Web design</p>

                    </a>
                  </li>

                  <li className="project-item  active" data-filter-item data-category="web design">
                    <a href="#">

                      <figure className="project-img">
                        <div className="project-item-icon-box">
                          <ion-icon name="eye-outline"></ion-icon>
                        </div>

                        <img src="./assets/images/project-6.png" alt="metaspark" loading="lazy"/>
                      </figure>

                      <h3 className="project-title">MetaSpark</h3>

                      <p className="project-category">Web design</p>

                    </a>
                  </li>

                  <li className="project-item  active" data-filter-item data-category="web development">
                    <a href="#">

                      <figure className="project-img">
                        <div className="project-item-icon-box">
                          <ion-icon name="eye-outline"></ion-icon>
                        </div>

                        <img src="./assets/images/project-7.png" alt="summary" loading="lazy"/>
                      </figure>

                      <h3 className="project-title">Summary</h3>

                      <p className="project-category">Web development</p>

                    </a>
                  </li>

                  <li className="project-item  active" data-filter-item data-category="applications">
                    <a href="#">

                      <figure className="project-img">
                        <div className="project-item-icon-box">
                          <ion-icon name="eye-outline"></ion-icon>
                        </div>

                        <img src="./assets/images/project-8.jpg" alt="task manager" loading="lazy"/>
                      </figure>

                      <h3 className="project-title">Task Manager</h3>

                      <p className="project-category">Applications</p>

                    </a>
                  </li>

                  <li className="project-item  active" data-filter-item data-category="web development">
                    <a href="#">

                      <figure className="project-img">
                        <div className="project-item-icon-box">
                          <ion-icon name="eye-outline"></ion-icon>
                        </div>

                        <img src="./assets/images/project-9.png" alt="arrival" loading="lazy"/>
                      </figure>

                      <h3 className="project-title">Arrival</h3>

                      <p className="project-category">Web development</p>

                    </a>
                  </li>

                </ul>

              </section>

            </article> */}

          {/* - #BLOG */}

            {/* <article className={`blog ${displaying=="blog" ? "active" : ""}`} data-page="blog">

              <header>
                <h2 className="h2 article-title">Blog</h2>
              </header>

              <section className="blog-posts">

                <ul className="blog-posts-list">

                  <li className="blog-post-item">
                    <a href="#">

                      <figure className="blog-banner-box">
                        <img src="./assets/images/blog-1.jpg" alt="Design conferences in 2022" loading="lazy"/>
                      </figure>

                      <div className="blog-content">

                        <div className="blog-meta">
                          <p className="blog-category">Design</p>

                          <span className="dot"></span>

                          <time datetime="2022-02-23">Fab 23, 2022</time>
                        </div>

                        <h3 className="h3 blog-item-title">Design conferences in 2022</h3>

                        <p className="blog-text">
                          Veritatis et quasi architecto beatae vitae dicta sunt, explicabo.
                        </p>

                      </div>

                    </a>
                  </li>

                  <li className="blog-post-item">
                    <a href="#">

                      <figure className="blog-banner-box">
                        <img src="./assets/images/blog-2.jpg" alt="Best fonts every designer" loading="lazy"/>
                      </figure>

                      <div className="blog-content">

                        <div className="blog-meta">
                          <p className="blog-category">Design</p>

                          <span className="dot"></span>

                          <time datetime="2022-02-23">Fab 23, 2022</time>
                        </div>

                        <h3 className="h3 blog-item-title">Best fonts every designer</h3>

                        <p className="blog-text">
                          Sed ut perspiciatis, nam libero tempore, cum soluta nobis est eligendi.
                        </p>

                      </div>

                    </a>
                  </li>

                  <li className="blog-post-item">
                    <a href="#">

                      <figure className="blog-banner-box">
                        <img src="./assets/images/blog-3.jpg" alt="Design digest #80" loading="lazy"/>
                      </figure>

                      <div className="blog-content">

                        <div className="blog-meta">
                          <p className="blog-category">Design</p>

                          <span className="dot"></span>

                          <time datetime="2022-02-23">Fab 23, 2022</time>
                        </div>

                        <h3 className="h3 blog-item-title">Design digest #80</h3>

                        <p className="blog-text">
                          Excepteur sint occaecat cupidatat no proident, quis nostrum exercitationem ullam corporis suscipit.
                        </p>

                      </div>

                    </a>
                  </li>

                  <li className="blog-post-item">
                    <a href="#">

                      <figure className="blog-banner-box">
                        <img src="./assets/images/blog-4.jpg" alt="UI interactions of the week" loading="lazy"/>
                      </figure>

                      <div className="blog-content">

                        <div className="blog-meta">
                          <p className="blog-category">Design</p>

                          <span className="dot"></span>

                          <time datetime="2022-02-23">Fab 23, 2022</time>
                        </div>

                        <h3 className="h3 blog-item-title">UI interactions of the week</h3>

                        <p className="blog-text">
                          Enim ad minim veniam, consectetur adipiscing elit, quis nostrud exercitation ullamco laboris nisi.
                        </p>

                      </div>

                    </a>
                  </li>

                  <li className="blog-post-item">
                    <a href="#">

                      <figure className="blog-banner-box">
                        <img src="./assets/images/blog-5.jpg" alt="The forgotten art of spacing" loading="lazy"/>
                      </figure>

                      <div className="blog-content">

                        <div className="blog-meta">
                          <p className="blog-category">Design</p>

                          <span className="dot"></span>

                          <time datetime="2022-02-23">Fab 23, 2022</time>
                        </div>

                        <h3 className="h3 blog-item-title">The forgotten art of spacing</h3>

                        <p className="blog-text">
                          Maxime placeat, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                        </p>

                      </div>

                    </a>
                  </li>

                  <li className="blog-post-item">
                    <a href="#">

                      <figure className="blog-banner-box">
                        <img src="./assets/images/blog-6.jpg" alt="Design digest #79" loading="lazy"/>
                      </figure>

                      <div className="blog-content">

                        <div className="blog-meta">
                          <p className="blog-category">Design</p>

                          <span className="dot"></span>

                          <time datetime="2022-02-23">Fab 23, 2022</time>
                        </div>

                        <h3 className="h3 blog-item-title">Design digest #79</h3>

                        <p className="blog-text">
                          Optio cumque nihil impedit uo minus quod maxime placeat, velit esse cillum.
                        </p>

                      </div>

                    </a>
                  </li>

                </ul>

              </section>

            </article> */}



          {/* - #CONTACT */}

            <article className={`contact ${displaying=="contact" ? "active" : ""}`} data-page="contact">

              <header>
                <h2 className="h2 article-title">Contact</h2>
              </header>

              <section className="mapbox" data-mapbox>
                <figure>
                  <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d199666.5651251294!2d-121.58334177520186!3d38.56165006739519!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x809ac672b28397f9%3A0x921f6aaa74197fdb!2sSacramento%2C%20CA%2C%20USA!5e0!3m2!1sen!2sbd!4v1647608789441!5m2!1sen!2sbd"
                    width="400" height="300" loading="lazy"></iframe>
                </figure>
              </section>

              <section className="contact-form">

                <h3 className="h3 form-title">Contact Form</h3>

                <form action="#" className="form" data-form>

                  <div className="input-wrapper">
                    <input type="text" name="fullname" className="form-input" placeholder="Full name" required data-form-input/>

                    <input type="email" name="email" className="form-input" placeholder="Email address" required data-form-input/>
                  </div>

                  <textarea name="message" className="form-input" placeholder="Your Message" required data-form-input></textarea>

                  <button className="form-btn" type="submit" disabled data-form-btn>
                    <ion-icon name="paper-plane"></ion-icon>
                    <span>Send Message</span>
                  </button>

                </form>

              </section>

            </article>

      </div>
      <script src="./assets/scripts/script.js"></script>

      <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
      <script noModule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>



    </main>


    </>
  )
}
